version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"


    #   build: ./flask - Instructs Docker to build the image using the Dockerfile found in the flask directory (relative to the docker-compose.yml file)
    #   container_name: flask - Gives our container the name of flask, also assigning it that hostname as we mentioned earlier
    #   restart: always - Makes the container always restart
    #   environment - A place for us to define environment variables for the container.
    #   expose - Exposes internal ports to other containers and services on the same network